### ISSUE TITLE
Plugin cannot be null

### ISSUE THREAD

**Issue by xgpjun** [602723113/ParticleLib#5]
当我使用java8去运行服务端（1.16.5）都是正常工作，可是使用java11~java17 则会抛出java.lang.IllegalArgumentException: Plugin cannot be null错误， 是我自己的原因吗？ 问题复现的  方式即为wiki中cube  这是为什么？

**Comment by xgpjun** [comment]
java11~java17分别使用的是1.16.5 和1.19.2

**Comment by 602723113** [comment]
有无完整的 Stacktrace

**Comment by xgpjun** [comment]
是这么样子的 我使用一个命令去调用wiki中的 在玩家位置生成正方体 提示Caused by: java.lang.IllegalArgumentException: Plugin cannot be null
	at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.validate(CraftScheduler.java:449) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:181) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:172) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.runTaskLater(CraftScheduler.java:136) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
	at top.zoyn.particlelib.pobject.ParticleObject.alwaysShowAsync(ParticleObject.java:93) ~[?:?]
	at cn.xgp.xgplottery.Command.SubCmd.HelpCommand.onCommand(HelpCommand.java:31) ~[?:?]
	at cn.xgp.xgplottery.Command.XgpLotteryCommand.onCommand(XgpLotteryCommand.java:31) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
	... 19 more

**Comment by 602723113** [comment]
我这边测试了 java17 下使用 paper1.19 无法复现

我这边建议你检查一下 XGPLottery 的 plugin.yml 有没有写 depend
```
depend:
  - ParticleLib
```
或
```
depend: [ParticleLib]
```

**Comment by xgpjun** [comment]
是我使用的方法有误吗？  我添加了depend的 java11  spigot-1.16.5  、  java17 1.19.2螺端也会报错、
```
@Override
    public boolean onCommand(@NotNull CommandSender sender, @NotNull Command command, @NotNull String label, @NotNull String[] args) {
        Location location = ((Player) sender).getLocation();
        Location loc1;
        Location loc2;
        loc1 = location.clone().add(0.1,0.1,0.1);
        loc2 = location.clone().add(0.9, 0.9, 0.9);
        Cube cube = new Cube(loc1, loc2);
        cube.setPeriod(1L)
                .setColor(Color.WHITE)
                .alwaysShow();
        return true;
    }
```

```
[145月2023 09:04:42.860] [Server thread/ERROR] [Minecraft/]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'test' in plugin TestPlugin v1.0-SNAPSHOT
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[arclight-1.19.2-1.0.1-0550c6cd.jar%23159!/:arclight-1.19.2-1.0.1-0550c6cd] {re:mixin,re:classloading}
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[arclight-1.19.2-1.0.1-0550c6cd.jar%23159!/:arclight-1.19.2-1.0.1-0550c6cd] {re:mixin,re:classloading}
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServerMixin.java:833) ~[arclight-1.19.2-1.0.1-0550c6cd.jar%23159!/:arclight-1.19.2-1.0.1-0550c6cd] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftServerMixin,pl:mixin:A}
	at org.bukkit.craftbukkit.v1_19_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:50) ~[arclight-1.19.2-1.0.1-0550c6cd.jar%23159!/:arclight-1.19.2-1.0.1-0550c6cd] {re:classloading}
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:263) ~[brigadier-1.0.18.jar%23107!/:?] {re:mixin}
	at net.minecraft.commands.Commands.m_242674_(CommandsMixin.java:240) ~[server-1.19.2-20220805.130853-srg.jar%23161!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.core.json:commands.CommandsMixin,pl:mixin:A}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_242600_(ServerPlayNetHandlerMixin.java:2872) ~[server-1.19.2-20220805.130853-srg.jar%23161!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:network.ServerPlayNetHandlerMixin,pl:mixin:APP:mixins.arclight.impl.forge.optimization.json:network.ServerGamePacketListenerImplMixin_Optimize,pl:mixin:A}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$12(ServerPlayNetHandlerMixin.java:1217) ~[server-1.19.2-20220805.130853-srg.jar%23161!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:network.ServerPlayNetHandlerMixin,pl:mixin:APP:mixins.arclight.impl.forge.optimization.json:network.ServerGamePacketListenerImplMixin_Optimize,pl:mixin:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_18693_(BlockableEventLoop.java:68) ~[server-1.19.2-20220805.130853-srg.jar%23161!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?] {}
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.19.2-20220805.130853-srg.jar%23161!/:?] {re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[server-1.19.2-20220805.130853-srg.jar%23161!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.19.2-20220805.130853-srg.jar%23161!/:?] {re:mixin,re:computing_frames,re:classloading}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServerMixin.java:763) ~[server-1.19.2-20220805.130853-srg.jar%23161!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServerMixin.java:157) ~[server-1.19.2-20220805.130853-srg.jar%23161!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[server-1.19.2-20220805.130853-srg.jar%23161!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServerMixin.java:746) ~[server-1.19.2-20220805.130853-srg.jar%23161!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServerMixin.java:740) ~[server-1.19.2-20220805.130853-srg.jar%23161!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140) ~[server-1.19.2-20220805.130853-srg.jar%23161!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServerMixin.java:726) ~[server-1.19.2-20220805.130853-srg.jar%23161!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2131) ~[server-1.19.2-20220805.130853-srg.jar%23161!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23161!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin}
Caused by: java.lang.IllegalArgumentException: Plugin cannot be null
	at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[arclight-forge-1.19.2-1.0.1.jar%2381!/:arclight-1.19.2-1.0.1-0550c6cd] {}
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.validate(CraftSchedulerMixin.java:464) ~[arclight-1.19.2-1.0.1-0550c6cd.jar%23159!/:arclight-1.19.2-1.0.1-0550c6cd] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftSchedulerMixin,pl:mixin:A}
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.runTaskTimer(CraftSchedulerMixin.java:196) ~[arclight-1.19.2-1.0.1-0550c6cd.jar%23159!/:arclight-1.19.2-1.0.1-0550c6cd] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftSchedulerMixin,pl:mixin:A}
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.runTaskTimer(CraftSchedulerMixin.java:187) ~[arclight-1.19.2-1.0.1-0550c6cd.jar%23159!/:arclight-1.19.2-1.0.1-0550c6cd] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftSchedulerMixin,pl:mixin:A}
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.runTaskLater(CraftSchedulerMixin.java:151) ~[arclight-1.19.2-1.0.1-0550c6cd.jar%23159!/:arclight-1.19.2-1.0.1-0550c6cd] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftSchedulerMixin,pl:mixin:A}
	at top.zoyn.particlelib.pobject.ParticleObject.alwaysShow(ParticleObject.java:70) ~[?:?] {}
	at test.testplugin.cmd.onCommand(TestPlugin.java:39) ~[?:?] {}
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[arclight-1.19.2-1.0.1-0550c6cd.jar%23159!/:arclight-1.19.2-1.0.1-0550c6cd] {re:mixin,re:classloading}
	... 22 more

```

**Comment by hpwriterkyle** [comment]
> 是我使用的方法有误吗？ 我添加了depend的 java11 spigot-1.16.5 、 java17 1.19.2螺端也会报错、
> 
> ```
> @Override
>     public boolean onCommand(@NotNull CommandSender sender, @NotNull Command command, @NotNull String label, @NotNull String[] args) {
>         Location location = ((Player) sender).getLocation();
>         Location loc1;
>         Location loc2;
>         loc1 = location.clone().add(0.1,0.1,0.1);
>         loc2 = location.clone().add(0.9, 0.9, 0.9);
>         Cube cube = new Cube(loc1, loc2);
>         cube.setPeriod(1L)
>                 .setColor(Color.WHITE)
>                 .alwaysShow();
>         return true;
>     }
> ```
> 
> ```
> [145月2023 09:04:42.860] [Server thread/ERROR] [Minecraft/]: null
> org.bukkit.command.CommandException: Unhandled exception executing command 'test' in plugin TestPlugin v1.0-SNAPSHOT
> 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[arclight-1.19.2-1.0.1-0550c6cd.jar%23159!/:arclight-1.19.2-1.0.1-0550c6cd] {re:mixin,re:classloading}
> 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[arclight-1.19.2-1.0.1-0550c6cd.jar%23159!/:arclight-1.19.2-1.0.1-0550c6cd] {re:mixin,re:classloading}
> 	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServerMixin.java:833) ~[arclight-1.19.2-1.0.1-0550c6cd.jar%23159!/:arclight-1.19.2-1.0.1-0550c6cd] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftServerMixin,pl:mixin:A}
> 	at org.bukkit.craftbukkit.v1_19_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:50) ~[arclight-1.19.2-1.0.1-0550c6cd.jar%23159!/:arclight-1.19.2-1.0.1-0550c6cd] {re:classloading}
> 	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:263) ~[brigadier-1.0.18.jar%23107!/:?] {re:mixin}
> 	at net.minecraft.commands.Commands.m_242674_(CommandsMixin.java:240) ~[server-1.19.2-20220805.130853-srg.jar%23161!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.core.json:commands.CommandsMixin,pl:mixin:A}
> 	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_242600_(ServerPlayNetHandlerMixin.java:2872) ~[server-1.19.2-20220805.130853-srg.jar%23161!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:network.ServerPlayNetHandlerMixin,pl:mixin:APP:mixins.arclight.impl.forge.optimization.json:network.ServerGamePacketListenerImplMixin_Optimize,pl:mixin:A}
> 	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$12(ServerPlayNetHandlerMixin.java:1217) ~[server-1.19.2-20220805.130853-srg.jar%23161!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:network.ServerPlayNetHandlerMixin,pl:mixin:APP:mixins.arclight.impl.forge.optimization.json:network.ServerGamePacketListenerImplMixin_Optimize,pl:mixin:A}
> 	at net.minecraft.util.thread.BlockableEventLoop.m_18693_(BlockableEventLoop.java:68) ~[server-1.19.2-20220805.130853-srg.jar%23161!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
> 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?] {}
> 	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.19.2-20220805.130853-srg.jar%23161!/:?] {re:classloading}
> 	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[server-1.19.2-20220805.130853-srg.jar%23161!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
> 	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.19.2-20220805.130853-srg.jar%23161!/:?] {re:mixin,re:computing_frames,re:classloading}
> 	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServerMixin.java:763) ~[server-1.19.2-20220805.130853-srg.jar%23161!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A}
> 	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServerMixin.java:157) ~[server-1.19.2-20220805.130853-srg.jar%23161!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A}
> 	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[server-1.19.2-20220805.130853-srg.jar%23161!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
> 	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServerMixin.java:746) ~[server-1.19.2-20220805.130853-srg.jar%23161!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A}
> 	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServerMixin.java:740) ~[server-1.19.2-20220805.130853-srg.jar%23161!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A}
> 	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140) ~[server-1.19.2-20220805.130853-srg.jar%23161!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
> 	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServerMixin.java:726) ~[server-1.19.2-20220805.130853-srg.jar%23161!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A}
> 	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2131) ~[server-1.19.2-20220805.130853-srg.jar%23161!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A}
> 	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23161!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A}
> 	at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin}
> Caused by: java.lang.IllegalArgumentException: Plugin cannot be null
> 	at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[arclight-forge-1.19.2-1.0.1.jar%2381!/:arclight-1.19.2-1.0.1-0550c6cd] {}
> 	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.validate(CraftSchedulerMixin.java:464) ~[arclight-1.19.2-1.0.1-0550c6cd.jar%23159!/:arclight-1.19.2-1.0.1-0550c6cd] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftSchedulerMixin,pl:mixin:A}
> 	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.runTaskTimer(CraftSchedulerMixin.java:196) ~[arclight-1.19.2-1.0.1-0550c6cd.jar%23159!/:arclight-1.19.2-1.0.1-0550c6cd] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftSchedulerMixin,pl:mixin:A}
> 	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.runTaskTimer(CraftSchedulerMixin.java:187) ~[arclight-1.19.2-1.0.1-0550c6cd.jar%23159!/:arclight-1.19.2-1.0.1-0550c6cd] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftSchedulerMixin,pl:mixin:A}
> 	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.runTaskLater(CraftSchedulerMixin.java:151) ~[arclight-1.19.2-1.0.1-0550c6cd.jar%23159!/:arclight-1.19.2-1.0.1-0550c6cd] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftSchedulerMixin,pl:mixin:A}
> 	at top.zoyn.particlelib.pobject.ParticleObject.alwaysShow(ParticleObject.java:70) ~[?:?] {}
> 	at test.testplugin.cmd.onCommand(TestPlugin.java:39) ~[?:?] {}
> 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[arclight-1.19.2-1.0.1-0550c6cd.jar%23159!/:arclight-1.19.2-1.0.1-0550c6cd] {re:mixin,re:classloading}
> 	... 22 more
> ```

请问其他插件是否正常工作呢uwu

**Comment by xgpjun** [comment]
> 
我添加了PlaceholderAPI依赖 它是可以正常工作的 uwu

**Comment by 602723113** [comment]
我使用 Java17 arclight-forge-1.19.3-1.0.3 也无法复现

这边我建议您尝试把 ParticleLib 更新至最新；或检查 `ParticleLib.getInstance()` 是否成功返回有值而不是null

在调用 alwayShow 时, ParticleLib 所建立的任务调度是以 ParticleLib 的名义进行调度，但不应当出现 ParticleLib.getInstance() 为 null 的情况，因此请在控制台当中检查 ParticleLib 是否已经成功加载并显示 `[ParticleLib] 粒子库已成功加载` 的字样

**Comment by xgpjun** [comment]
加载成功的消息是有的 
```
[10:25:36] [Server thread/INFO]: [ParticleLib] Enabling ParticleLib v1.5.1
[10:25:36] [Server thread/INFO]: [ParticleLib] 粒子库已成功加载
[10:25:36] [Server thread/INFO]: [TestPlugin] Enabling TestPlugin v1.0-SNAPSHOT
```
而 调用ParticleLib.getInstance()的返回值为null 
另外我发现maven下载的1.5.1只有109KB 与本页面的release好像不同， 但似乎好像跟这个没太大关系

**Comment by 602723113** [comment]
914085636 加群聊吧，现在没啥思路

**Comment by xgpjun** [comment]
加了 有空同意下捏
